apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: mediawiki
        image: mediawiki:latest
        env:
          - name: MEDIAWIKI_DB_HOST
            value: mariadb
          - name: MEDIAWIKI_DB_USER
            value: wikiuser
          - name: MEDIAWIKI_DB_PASSWORD
            value: wikisecret
          - name: MEDIAWIKI_DB_NAME
            value: mediawiki
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: mediawiki
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer